### ISSUE TITLE
[TODO] Centre entities on tiles

### ISSUE THREAD

**Issue by KOOKIIEStudios** [KOOKIIEStudios/Califorknia#18]
**What needs to be done?**
Entities are not currently centred properly, since coordinates start from top right in PyGame.

**When should this be done by? (optional)**
This iteration

**Any other details? (optional)**
Make use of the width/height to dynamically calculate the offset for the x-/y-coordinates when rendering the entity

**Comment by ta-lyx** [comment]
This is resolved.
