### ISSUE TITLE
[TODO] Fix grass and water tile disappearing 

### ISSUE THREAD

**Issue by ta-lyx** [KOOKIIEStudios/Califorknia#20]
**What needs to be done?**
Make the water and grass tile stay after player walks over it

**When should this be done by? (optional)**

**Any other details? (optional)**
When player walks over a grass or water tile, the tile disappears and is replaced with tile 49.

**Comment by KOOKIIEStudios** [comment]
Will be fixed by #17, until our maps become bigger than the screen.

I have to assume the map is screen-sized right now, because we haven't decided how to handle camera panning yet.

**Comment by KOOKIIEStudios** [comment]
This has been resolved as of f9851de74b6a411af1d9d10232ae75f680eddfd1
